name: Publish packages to npm
on:
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
          # Defaults to the user or organization that owns the workflow file
          scope: "mozilla"
      - run: npm install -g @microsoft/rush
      - run: git config --global user.email "build@mozilla.com"
      - run: rush version --bump
      - run: rush update
      - run: rush install
      - run: rush build
      - run: rush test
      - run: rush publish --include-all -p --force
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "Mozilla Rally Github CI/CD"
          author_email: "build@mozilla.com"
          message: "Bump versions [skip ci]"
          add: "*"
