name: Publish npm packages and Firebase functions
on:
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
          # Defaults to the user or organization that owns the workflow file
          scope: "mozilla"
      - run: npm install -g @microsoft/rush
      - run: git config --global user.email "build@mozilla.com"
      - run: rush version --bump
      - run: rush update
      - run: rush install
      - run: rush build
      - run: rush test
      - run: rush publish --include-all -p --force
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Archive Rally Extension zip
        uses: actions/upload-artifact@v3
        with:
          name: rally-extension
          path: |
              extensions/rally-extension/web-ext-artifacts/

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "Mozilla Rally Github CI/CD"
          author_email: "build@mozilla.com"
          message: "Bump versions [skip ci]"
          add: "*"

      - uses: marceloprado/has-changed-path@v1
        id: changed-functions
        with:
          paths: web-platform/functions

      - name: Deploy firebase functions to production
        if: steps.changed-functions.outputs.changed == 'true'
        run: |
          cp web-platform/firebase/firebase.config.rally-web-prod.json web-platform/firebase.config.json
          cp web-platform/firebase/firestore.rules web-platform/firestore.rules
          cp web-platform/firebase/firebase.json web-platform/firebase.json
          sed -i 's/\.\.\/functions/functions/g' web-platform/firebase.json
          echo ${{ secrets.GCLOUD_SERVICE_KEY }} | base64 --decode --ignore-garbage > "$HOME"/gcloud.json
          GOOGLE_APPLICATION_CREDENTIALS="$HOME"/gcloud.json web-platform/functions/node_modules/.bin/firebase deploy --only functions,firestore --project ${{secrets.PROJECT_ID_PROD}} -c web-platform/firebase.json
